<a href="https://colab.research.google.com/github/Daeun-Danna-Lee/DSC3032-Deep-Learning-1-Foundations-and-Image-Processing/blob/main/LDE_lab02b_pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 2b – Tensors

In [2]:
import torch

## Create empty tensors
- Uninitialised tensors

In [ ]:
# 1-D
x = torch.empty(1)
print(x)

# 1-D with two elements
x = torch.empty(2)
print(f"\n1-D tensor\n{x}\n")

# 2-D
x = torch.empty(2,3)
print(f"2-D tensor\n{x}\n")

# 3-D
x = torch.empty(2,3,1)
print("3-D tensor\n",x)


tensor([-6.0276e+17])

1-D tensor
tensor([-6.0278e+17,  3.0789e-41])

2-D tensor
tensor([[-6.0279e+17,  3.0789e-41,  5.0447e-44],
        [ 0.0000e+00,         nan,  0.0000e+00]])

3-D tensor
 tensor([[[-6.0278e+17],
         [ 3.0789e-41],
         [ 5.0447e-44]],

        [[ 0.0000e+00],
         [        nan],
         [ 0.0000e+00]]])


## Initialise tensors to scalar, random values, zeros or ones

In [ ]:
# 0-D tensor (just containing scalar value 3)
x = torch.tensor(3)
print(f'Scalar: {x} has shape {x.shape} and {x.ndim} dimensions\n')

# Random values in the interval [0,1]
x = torch.rand(2,3)
print(f"Random values:\n{x}")
print(x.dtype)

# Zeros
x = torch.zeros(2,3)
print(f"\nZeros:\n{x}")
print(x.dtype)

x = torch.zeros(2,3, dtype=torch.int)
print(f"\nZeros:\n{x}\n")

# Ones
x = torch.ones(2,3)
print(f"Ones:\n{x}")
print(f"Type: {x.dtype}\n")

x = torch.ones(2,3, dtype=torch.double)
print(f"Ones:\n{x}")

Scalar: 3 has shape torch.Size([]) and 0 dimensions

Random values:
tensor([[0.4996, 0.7491, 0.0885],
        [0.0020, 0.7871, 0.8457]])
torch.float32

Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32

Zeros:
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.float32

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## Construct tensor from data

In [ ]:
# Change a list to a tensor
x = torch.tensor([0.5, 2.7])
print(x)

tensor([0.5000, 2.7000])


### Changing tensor data type


In [ ]:
x = torch.rand(2,3) * 20
print(x)

# Change to integer
y = x.to(torch.int32)
print(y)

tensor([[ 6.7044,  7.1875,  5.1709],
        [19.9458,  9.0731, 16.1240]])
tensor([[ 6,  7,  5],
        [19,  9, 16]], dtype=torch.int32)


### Create a separate copy



In [ ]:
a = torch.ones(2, 2)
b = a.clone()

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[1., 1.],
        [1., 1.]])


## Basic tensor operations

- addition, subtraction, multiplication, division

In [ ]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

z = torch.add(x,y) # same as z = x + y
print("x + y = ")
print(z)

z = torch.sub(x,y) # same as z = x - y
print("x - y = ")
print(z)

z = torch.mul(x,y) # same as z = x * y
print("x * y = ")
print(z)

z = torch.div(x,y) # same as z = x / y
print("x / y = ")
print(z)


x = 
tensor([[0.5169, 0.4687],
        [0.0945, 0.2002]])

y = 
tensor([[0.0873, 0.3404],
        [0.6591, 0.4333]])

x + y = 
tensor([[0.6042, 0.8091],
        [0.7536, 0.6335]])
x - y = 
tensor([[ 0.4296,  0.1282],
        [-0.5647, -0.2330]])
x * y = 
tensor([[0.0451, 0.1595],
        [0.0623, 0.0868]])
x / y = 
tensor([[5.9194, 1.3767],
        [0.1433, 0.4622]])


### Inplace operations

- any function with a trailing underscore (e.g. ``add_``) will modify the value of the variable in question, in place

In [ ]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

# Inplace operations
y.add_(x) # modify y by adding x to it
print(f"y + x = {y}")

y.sub_(x) # modify y by subtracting x from it
print(f"y - x = {y}")

y.mul_(x) # modify y by multiplying x to it
print(f"y * x = {y}")

y.div_(x) # modify y by dividing it by x
print(f"y / x = {y}")


x = 
tensor([[0.5586, 0.1001],
        [0.0762, 0.9484]])

y = 
tensor([[0.0188, 0.2372],
        [0.6615, 0.5568]])

y + x = tensor([[0.5774, 0.3372],
        [0.7377, 1.5051]])
y - x = tensor([[0.0188, 0.2372],
        [0.6615, 0.5568]])
y * x = tensor([[0.0105, 0.0237],
        [0.0504, 0.5280]])
y / x = tensor([[0.0188, 0.2372],
        [0.6615, 0.5568]])


## Accessing tensors

In [ ]:
# Slicing
x = torch.rand(5,3)
print(x)

# Get all rows but only first column
print(x[:, 0])

# Get all columns but only the second row
print(x[1, :])

# Get a specific element
print(x[2,2])

# When the tensor returns only ONE element, use item() to get the actual value of that element
print(x[1,1].item())

y = torch.tensor([2.0])
print(y.item())

## Tensor Shape & Dimensions
- The number of dimensions a tensor has is called its rank and the length in each dimension describes its ``shape``.
- To determine the length of each dimension, call ``.shape``
- To determine the number of dimensions it has, call ``.ndim``


In [ ]:
x = torch.rand(5,3)
print(f'{x} \nhas shape {x.shape} and {x.ndim} dimensions\n')

## More on Shapes

- `[1,5,2,6]` has shape (4,) to indicate it has 4 elements and the missing element after the comma means it is a 1-D tensor or array (vector)
- `[[1,5,2,6], [1,2,3,1]]` has shape (2,4) to indicate it has 2 elements (rows) and each of these have 4 elements (columns). This is a 2-D tensor or array (matrix or a list of vectors)
- `[[[1,5,2,6], [1,2,3,1]], [[5,2,1,2], [6,4,3,2]], [[7,8,5,3], [2,2,9,6]]]` has shape (3, 2, 4) to indicate it has 3 elements in the first dimension, and each of these contain 2 elements and each of these contain 4 elements. This is a 3-D tensor or array


## Operations on tensor dimensions
- A tensor dimension is akin to an array's axis. The number of dimensions is called rank.
- A scalar has rank 0, a vector has rank 1, a matrix has rank 2, a cuboid has rank 3, etc.
- Sometimes one wants to do an operation only on a particular dimension, e.g. on the rows only
- Across ``dim=X`` means we do the operation w.r.t to the dimension given and the rest of the dimensions of the tensor stays as they are
- in 2-D tensors, ``dim=0`` refers to the columns while ``dim=1`` refers to the rows


In [ ]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])

print(x.shape)
print(f'Summing across dim=0 (columns) gives: {torch.sum(x,dim=0)}')

print(f'Summing across dim=1 (rows) gives: {torch.sum(x,dim=1)}')


## Reshaping tensors
- There are several ways to do this but using ``torch.reshape()`` is the most common
- Also look up ``torch.squeeze(), torch.unsqueeze()`` and ``torch.view()``


In [ ]:
x = torch.rand(4,4)
print("Original:")
print(x)
print(x.shape)

# Reshape (flatten) to 1-D
y = x.reshape(16) # number of elements must be the same as original, error otherwise
print("Reshaped to 1-D:")
print(y)

# Reshape to 2-D
y = x.reshape(8,2)
print("Reshaped to 2-D:")
print(y)

# Could leave out one of the dimensions by specifying -1
y = x.reshape(2, -1)
print("Reshaped to 2 x Unspecified 2-D:")
print(y)
print(y.shape)

# Could use unsqueeze(0) to add a dimension at position 0
y = x.unsqueeze(0)
print(f'Using unsqueeze(0) to add dimension from original shape {x.shape} to {y.shape}')

## Convert between NumPy and PyTorch tensors

- Tensors can work on CPUs and GPUs
- NumPy arrays can only work on CPUs

In [ ]:
import torch
import numpy as np

# Tensor to NumPy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

# b changes when a is modified because they share the same memory space!
a.add_(1)
print(a)
print(b)

In [ ]:
import torch
import numpy as np

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

# Modifying array will modify the tensor as well
a += 2
print(a)
print(b)

# Exercise

In [3]:
# 1. Create a tensor of 100 equally spaced numbers from 0 to 2.
# Assign the tensor to x (Hint: use torch.linspace() )
x = torch.linspace(0, 2, 100)

# Print x
print(x)

tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808, 0.1010, 0.1212, 0.1414, 0.1616,
        0.1818, 0.2020, 0.2222, 0.2424, 0.2626, 0.2828, 0.3030, 0.3232, 0.3434,
        0.3636, 0.3838, 0.4040, 0.4242, 0.4444, 0.4646, 0.4848, 0.5051, 0.5253,
        0.5455, 0.5657, 0.5859, 0.6061, 0.6263, 0.6465, 0.6667, 0.6869, 0.7071,
        0.7273, 0.7475, 0.7677, 0.7879, 0.8081, 0.8283, 0.8485, 0.8687, 0.8889,
        0.9091, 0.9293, 0.9495, 0.9697, 0.9899, 1.0101, 1.0303, 1.0505, 1.0707,
        1.0909, 1.1111, 1.1313, 1.1515, 1.1717, 1.1919, 1.2121, 1.2323, 1.2525,
        1.2727, 1.2929, 1.3131, 1.3333, 1.3535, 1.3737, 1.3939, 1.4141, 1.4343,
        1.4545, 1.4747, 1.4949, 1.5152, 1.5354, 1.5556, 1.5758, 1.5960, 1.6162,
        1.6364, 1.6566, 1.6768, 1.6970, 1.7172, 1.7374, 1.7576, 1.7778, 1.7980,
        1.8182, 1.8384, 1.8586, 1.8788, 1.8990, 1.9192, 1.9394, 1.9596, 1.9798,
        2.0000])


In [5]:
# 3. Print the first 5 numbers in x.
print(x[:5])

# 4. Print the last 5 numbers in x
print(x[-5:])

tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808])
tensor([1.9192, 1.9394, 1.9596, 1.9798, 2.0000])


In [6]:
# 5. Create another tensor of 100 random values between 0 and 1.
# Assign the tensor to y (Hint: use torch.rand() )
y = torch.rand(100)

# Print y
print(y)

tensor([0.9460, 0.4955, 0.2558, 0.8057, 0.8946, 0.1908, 0.8680, 0.4461, 0.7542,
        0.7817, 0.7043, 0.4110, 0.6490, 0.2202, 0.0651, 0.2421, 0.4005, 0.0953,
        0.2357, 0.1501, 0.4231, 0.5264, 0.1079, 0.6403, 0.9358, 0.1437, 0.7637,
        0.9527, 0.5059, 0.0783, 0.3313, 0.9624, 0.4867, 0.7159, 0.0216, 0.9729,
        0.1445, 0.9912, 0.7065, 0.4402, 0.9152, 0.4096, 0.0035, 0.4001, 0.9128,
        0.7320, 0.7262, 0.4299, 0.8767, 0.9280, 0.3704, 0.7142, 0.3828, 0.0358,
        0.3004, 0.9013, 0.4511, 0.7748, 0.7221, 0.5459, 0.8182, 0.7978, 0.0100,
        0.7805, 0.3762, 0.6941, 0.3997, 0.2398, 0.4852, 0.2943, 0.2519, 0.5475,
        0.1109, 0.4413, 0.9988, 0.3521, 0.6020, 0.8042, 0.9803, 0.2024, 0.8025,
        0.2840, 0.3738, 0.6714, 0.6338, 0.7009, 0.3994, 0.2815, 0.8065, 0.1880,
        0.5809, 0.0165, 0.3997, 0.2710, 0.1610, 0.9879, 0.0631, 0.1285, 0.8672,
        0.3042])


In [7]:
# 6. Multiply x and y, store the result in z
z = torch.mul(x, y)

# Print z
print(z)

tensor([0.0000, 0.0100, 0.0103, 0.0488, 0.0723, 0.0193, 0.1052, 0.0631, 0.1219,
        0.1421, 0.1423, 0.0913, 0.1573, 0.0578, 0.0184, 0.0734, 0.1294, 0.0327,
        0.0857, 0.0576, 0.1709, 0.2233, 0.0479, 0.2975, 0.4537, 0.0726, 0.4011,
        0.5197, 0.2862, 0.0459, 0.2008, 0.6027, 0.3146, 0.4773, 0.0148, 0.6879,
        0.1051, 0.7409, 0.5424, 0.3468, 0.7395, 0.3393, 0.0030, 0.3476, 0.8113,
        0.6654, 0.6748, 0.4081, 0.8501, 0.9186, 0.3741, 0.7358, 0.4021, 0.0383,
        0.3277, 1.0014, 0.5103, 0.8922, 0.8461, 0.6506, 0.9918, 0.9832, 0.0126,
        0.9934, 0.4864, 0.9115, 0.5330, 0.3246, 0.6666, 0.4103, 0.3562, 0.7852,
        0.1613, 0.6508, 1.4932, 0.5335, 0.9243, 1.2510, 1.5448, 0.3230, 1.2969,
        0.4647, 0.6192, 1.1258, 1.0755, 1.2035, 0.6939, 0.4948, 1.4338, 0.3380,
        1.0562, 0.0303, 0.7430, 0.5091, 0.3057, 1.8960, 0.1223, 0.2519, 1.7170,
        0.6083])


In [9]:
# 7. Reshape z to a tensor with 5 rows and 20 columns
# Store reshaped tensor to z2
z2 = z.reshape(5, 20)

# Print z2
print(z2)

tensor([[0.0000, 0.0100, 0.0103, 0.0488, 0.0723, 0.0193, 0.1052, 0.0631, 0.1219,
         0.1421, 0.1423, 0.0913, 0.1573, 0.0578, 0.0184, 0.0734, 0.1294, 0.0327,
         0.0857, 0.0576],
        [0.1709, 0.2233, 0.0479, 0.2975, 0.4537, 0.0726, 0.4011, 0.5197, 0.2862,
         0.0459, 0.2008, 0.6027, 0.3146, 0.4773, 0.0148, 0.6879, 0.1051, 0.7409,
         0.5424, 0.3468],
        [0.7395, 0.3393, 0.0030, 0.3476, 0.8113, 0.6654, 0.6748, 0.4081, 0.8501,
         0.9186, 0.3741, 0.7358, 0.4021, 0.0383, 0.3277, 1.0014, 0.5103, 0.8922,
         0.8461, 0.6506],
        [0.9918, 0.9832, 0.0126, 0.9934, 0.4864, 0.9115, 0.5330, 0.3246, 0.6666,
         0.4103, 0.3562, 0.7852, 0.1613, 0.6508, 1.4932, 0.5335, 0.9243, 1.2510,
         1.5448, 0.3230],
        [1.2969, 0.4647, 0.6192, 1.1258, 1.0755, 1.2035, 0.6939, 0.4948, 1.4338,
         0.3380, 1.0562, 0.0303, 0.7430, 0.5091, 0.3057, 1.8960, 0.1223, 0.2519,
         1.7170, 0.6083]])


In [10]:
# 8. Get the sum of each row in z2
print(torch.sum(z2, dim=1))

# 9. Get the mean of each column in z2
print(torch.sum(z2, dim=0))

tensor([ 1.4391,  6.5522, 11.5365, 14.3365, 15.9859])
tensor([3.1992, 2.0205, 0.6930, 2.8131, 2.8992, 2.8723, 2.4080, 1.8103, 3.3586,
        1.8549, 2.1296, 2.2455, 1.7784, 1.7333, 2.1599, 4.1922, 1.7914, 3.1687,
        4.7359, 1.9864])


In [19]:
# 10. Reshape z to a 3D tensor (keep all the elements)
# Store reshaped tensor to z3
z3 = z.reshape(2, 5, 10)

# Print z3
print(z3)

tensor([[[0.0000, 0.0100, 0.0103, 0.0488, 0.0723, 0.0193, 0.1052, 0.0631,
          0.1219, 0.1421],
         [0.1423, 0.0913, 0.1573, 0.0578, 0.0184, 0.0734, 0.1294, 0.0327,
          0.0857, 0.0576],
         [0.1709, 0.2233, 0.0479, 0.2975, 0.4537, 0.0726, 0.4011, 0.5197,
          0.2862, 0.0459],
         [0.2008, 0.6027, 0.3146, 0.4773, 0.0148, 0.6879, 0.1051, 0.7409,
          0.5424, 0.3468],
         [0.7395, 0.3393, 0.0030, 0.3476, 0.8113, 0.6654, 0.6748, 0.4081,
          0.8501, 0.9186]],

        [[0.3741, 0.7358, 0.4021, 0.0383, 0.3277, 1.0014, 0.5103, 0.8922,
          0.8461, 0.6506],
         [0.9918, 0.9832, 0.0126, 0.9934, 0.4864, 0.9115, 0.5330, 0.3246,
          0.6666, 0.4103],
         [0.3562, 0.7852, 0.1613, 0.6508, 1.4932, 0.5335, 0.9243, 1.2510,
          1.5448, 0.3230],
         [1.2969, 0.4647, 0.6192, 1.1258, 1.0755, 1.2035, 0.6939, 0.4948,
          1.4338, 0.3380],
         [1.0562, 0.0303, 0.7430, 0.5091, 0.3057, 1.8960, 0.1223, 0.2519,
          1.717